pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('app') {
                    sh 'mvn clean package'
                }
            }
        }

	stage('Docker Build') {
    	    steps {
        	sh 'docker build -t bankpro-app -f docker/Dockerfile .'
    	    }
        }

	stage('Docker Info') {
    	    steps {
        	sh 'whoami'
        	sh 'docker version'
        	sh 'docker ps'
    	    }
	}

        stage('Deploy via Ansible') {
            steps {
                sh 'ansible-playbook -i ansible/inventory.ini ansible/deploy.yml'
            }
        }
    }
}
