- hosts: aws
  become: yes

  tasks:
    - name: Pull latest image
      shell: docker pull nalinivk/bankpro-app:latest

    - name: Stop running container
      shell: docker stop bankpro || true

    - name: Remove old container
      shell: docker rm bankpro || true

    - name: Run new container
      shell: |
        docker rm -f bankpro || true
        docker run -d -p 8081:8080 --name bankpro nalinivk/bankpro-app:latest
